### ISSUE TITLE
Build 3p wheels in actions

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_py#1]
`numpy` is the gold standard of a package that's hard to build.

**Comment by dmeister** [comment]
This would be incredible useful.

**Comment by alexeagle** [comment]
We're collaborating with @jvolkman since https://github.com/jvolkman/rules_pycross does a pretty good job of this

**Comment by alexeagle** [comment]
Out of scope, it seems that rules_python will have a solution for this by absorbing rules_pycross
