### ISSUE TITLE
[FR]: Virtual environments to be created next to the target

### ISSUE THREAD

**Issue by psalvaggio-dl** [aspect-build/rules_py#110]
### What is the current behavior?

Running a `.venv` target will create the virtual environment in the root of the repo, with the name `.<target>.venv`. The virtual environment is not inherently relocatable due to the relative paths inside of `first_party.pth`.

### Describe the feature

Allow for the virtual environments to be created in the same directory as the rule is defined. The current default naming behavior is fine, but adding support for:
```
bazel run :target.venv env
```
to name the resulting virtual environment would be great!

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by rbuckland** [comment]
Yes this would be beneficial.

**Comment by jsharpe** [comment]
The relative paths also cause issues if you want to package `py_binary` targets into tar balls using `rules_pkg` as the output file structure is different to when it is extracted in tree.
