### ISSUE TITLE
[FR]: Produce an archive file for a py_binary that packages the virtualenv

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_py#114]
### Describe the feature

This is useful to get a deployment target which matches the python expectation to resolve at runtime

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by mattem** [comment]
Would you expect it to package the interpreter? If so, perhaps we could leverage py oxidizer.

**Comment by alexeagle** [comment]
I think https://github.com/aspect-build/rules_py/blob/main/docs/pex.md satisfied the original intent here. It does *not* include an interpreter, but we're not intending to replace the [python_zip_file feature](https://github.com/bazelbuild/bazel/pull/9453)

If someone wants more from rules_py here, please open another issue.
