### ISSUE TITLE
py_test macro passes testonly attributes to py_venv

### ISSUE THREAD

**Issue by mattem** [aspect-build/rules_py#15]
Attributes like `size` etc that are for tests get passed though to `py_venv` in the `py_test` macro, causing bazel to error.

**Comment by alexeagle** [comment]
Just found that this breaks `bazel run //my:test.venv` for making a virtual env for debugging tests:

```
ERROR: /Users/alexeagle/Projects/try_python/app/BUILD.bazel:19:8: in _py_venv rule //app:app_test.venv: non-test target '//app:app_test.venv' depends on testonly target '//app:__test__' and doesn't have testonly attribute set
```

I'm surprised no one ran into that...

**Comment by stagnation** [comment]
Thanks! We saw this with some queries that would fail too, I forgot exactly which, but probably an `rdeps` over a monorepo. A lot of things tend to break then, but it is better to have it fixed before trying to troubleshoot something with an `rdeps` and finding that it does not work. Thanks a bunch :+1:
