### ISSUE TITLE
[FR]: Produce a container image

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_py#151]
### Describe the feature

Probably using rules_oci.

It would be nice to show it working with AWS lambda which has a particular layout required in the image.

**Comment by kpark-hrp** [comment]
I would love a documentation on how to do this

**Comment by alexeagle** [comment]
Thulio nearly has this working.

**Comment by thesayyn** [comment]
https://github.com/aspect-build/bazel-examples/pull/256

**Comment by alexeagle** [comment]
That one is rules_python py_binary though?

**Comment by thesayyn** [comment]
> That one is rules_python py_binary though?

They are orthogonal. py_binary is interchangeable. Should I make the example use rules_py by default?

**Comment by alexeagle** [comment]
Yeah the example needs to be rules_py instead, and I hope that makes it more compatible

**Comment by alexeagle** [comment]
Finished in https://github.com/aspect-build/bazel-examples/pull/282
