### ISSUE TITLE
[FR]: doc: Custom Python interpreter needs to have pip installed

### ISSUE THREAD

**Issue by georgevreilly** [aspect-build/rules_py#176]
### Describe the feature

We build a custom Python interpreter into an artifact, which is downloaded at build time. To get `rules_py` to work, I had to update our interpreter build script to run `bin/python -m ensurepip` so that the `pip` package was installed at `lib/python3.8/site-packages` in the tarball. Otherwise, the `rules_py` virtualenv stuff fails miserably.

Please document any assumptions about the Python interpreter.

**Comment by alexeagle** [comment]
#33 suggests that we could drop the dependency on `pip` being supplied with the interpreter. But for 1.0 I think we'll just document this as being required as you suggest.

**Comment by mattem** [comment]
Will be resolved by #233
