### ISSUE TITLE
Investigate PyCharm issue with .pth files

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_py#2]

**Comment by mattem** [comment]
Opened upstream issue https://youtrack.jetbrains.com/issue/IDEA-294464/pth-files-inside-a-venv-site-packages-is-ignored with minimal non-bazel repro https://github.com/mattem/ij-venv-pth

**Comment by alexeagle** [comment]
Fixed upstream, users need a new enough PyCharm.
