### ISSUE TITLE
[FR]: py_image_layer

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_py#212]
### What is the current behavior?

Users have to paste some starlark into their projects.

### Describe the feature

I think we can get to a public API similar to js_image_layer that we're able to commit to, and add to this repository.

**Comment by thesayyn** [comment]
Note that now we have bsdtar toolchain in bazel-lib, we can do this with no runtime code needed.

**Comment by alexeagle** [comment]
I want this now to make `aspect init` nice: https://github.com/aspect-build/aspect-workflows-template/issues/60

**Comment by alexeagle** [comment]
was added in #402
