### ISSUE TITLE
[Bug]: py_binary breaks cross_platform build when building image with rules_oci

### ISSUE THREAD

**Issue by lyao-77** [aspect-build/rules_py#218]
### What happened?

When we use `py_binary` to build docker images with rules_oci, we couldn't build the tarball for ubuntu images. The error log:

> ERROR: /Users/lyao/bazel/bazel-examples/oci_python_image/hello_world/BUILD.bazel:18:10: Creating virtual environment for //hello_world:hello_world failed: (Exit 126): sandbox-exec failed: error executing command 
>   (cd /private/var/tmp/_bazel_lyao/1e813cdbb954646ce252ec3692bb82d4/sandbox/darwin-sandbox/10/execroot/_main && \
>   exec env - \
>     TMPDIR=/var/folders/gm/r7n8598x7zq6rwkd1_r75_3h0000gp/T/ \
>   /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_lyao/1e813cdbb954646ce252ec3692bb82d4/sandbox/darwin-sandbox/10/sandbox.sb /var/tmp/_bazel_lyao/install/7d4a2659eff664c24e2f7d717eef5139/process-wrapper '--timeout=0' '--kill_delay=15' '--stats=/private/var/tmp/_bazel_lyao/1e813cdbb954646ce252ec3692bb82d4/sandbox/darwin-sandbox/10/stats.out' /bin/bash -c bazel-out/darwin_arm64-fastbuild-ST-baeacbe55d95/bin/hello_world/hello_world.venv_venv.sh)
> bazel-out/darwin_arm64-fastbuild-ST-baeacbe55d95/bin/hello_world/hello_world.venv_venv.sh: line 38: external/rules_python~0.21.0~python~python3_9_aarch64-unknown-linux-gnu/bin/python3: cannot execute binary file
> INFO: Elapsed time: 0.763s, Critical Path: 0.37s
> INFO: 3 processes: 3 internal.
> FAILED: Build did NOT complete successfully

I'm using https://github.com/aspect-build/bazel-examples/tree/main/oci_python_image to reproduce the error.

The issue seems relate to the wrong python interpreter path and is not platform agnostic when calling venv.

I tried the following command with Mac as a workaround:
`❯ bazel build //... --sandbox_debug --platform=//hello_world:x86_64_linux`
it ran into the same issue (different error) and seems the current implementation of py_binary breaks the cross-platform build.

### Version

Development (host) and target OS/architectures:
host: Mac with M1
target OS/arch: linux

Output of `bazel --version`:
bazel 6.2.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
the same as the example: https://github.com/aspect-build/bazel-examples

Language(s) and/or frameworks involved:

### How to reproduce

build the example "oci_python_image" with Mac

**Comment by euan-cowie** [comment]
I'm having the exact same issue. Did you manage to solve or find a workaround? Will let you know if I do.

**Comment by mattem** [comment]
Will be resolved by #233
