### ISSUE TITLE
[Bug]: Dependencies missing from `py_venv`

### ISSUE THREAD

**Issue by RyanDraves** [aspect-build/rules_py#255]
### What happened?

When creating a venv with the `py_venv` rule, none of the libraries installed with `pip` are exported.

### Version

Development (host) and target OS/architectures: Ubuntu x86_64

Output of `bazel --version`: bazel 7.0.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: `aspect_rules_py = 0.5.0` or `HEAD`, `rules_python = 0.29.0`

Language(s) and/or frameworks involved:
Python

### How to reproduce

Minimal example:

MODULE.bazel:
```starlark
bazel_dep(name = "aspect_rules_py", version = "0.5.0")

bazel_dep(name = "rules_python", version = "0.29.0")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")

python.toolchain(
    python_version = "3.10",
    is_default = True,
)

use_repo(python, "python_versions")

register_toolchains("@python_versions//:all")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")

pip.parse(
    hub_name = "pip",
    python_version = "3.10",
    requirements_lock = "//:requirements_lock.txt",
)

use_repo(pip, "pip")
```

requirements_lock.txt:
```
pyserial==3.5 \
    --hash=sha256:3c77e014170dfffbd816e6ffc205e9842efb10be9f58ec16d3e8675b4925cddb \
    --hash=sha256:c4451db6ba391ca6ca299fb3ec7bae67a5c55dde170964c7a14ceefec02f2cf0
    # via -r requirements.txt
```

BUILD:
```starlark
load("@aspect_rules_py//py:defs.bzl", "py_venv")
load("@pip//:requirements.bzl", "all_requirements")

py_venv(
    name = "venv",
    deps = all_requirements,
)
```

Commands:
- `bazel run //:venv`
- `.venv/bin/python`
  - `import serial` (or inspect `.venv` and see that `pyserial` is missing)

**Comment by mattem** [comment]
This is the same as #248
