### ISSUE TITLE
[FR]: Simple stand-alone example for a project using rules_py

### ISSUE THREAD

**Issue by kopp** [aspect-build/rules_py#259]
### What is the current behavior?

The only available example that uses rules_py is within the `rules_py` repository.  Hence the WORKSPACE and BUILD files contain more than what is necessary to just use the rules.

### Describe the feature

A simple stand-alone repository, e.g. `https://github.com/aspect-build/bazel-examples/tree/main/rules_py/`, that contains a minimal application (e.g. one library, one executable), that uses `rules_py` to define those.  It should have at least one external dependency.  This should enable users that want to use `rules_py` to start a project by adapting the given example.

https://github.com/aspect-build/bazel-examples/tree/main/oci_python_image is already quite close, but comes bundled with docker, which adds some more complexity.

**Comment by alexeagle** [comment]
Our convention is that while `examples` is in the root WORKSPACE, the e2e/ folders act as standalone examples.

I'll leave this open since I do think we'll add more examples to aspect-build/bazel-examples or bazelbuild/examples as part of 1.0.

**Comment by alexeagle** [comment]
we now have `aspect init` in our CLI which creates a new minimal rules_py project. I think that's as good as a standalone example. You can look in https://github.com/aspect-build/aspect-workflows-template for the scaffold that's used to stamp out a new project.
