### ISSUE TITLE
[Bug]: sha256sum changed on commit 82ad68fe2e6ba695a528a8748a2f796c1da8c4c0

### ISSUE THREAD

**Issue by blackliner** [aspect-build/rules_py#278]
### What happened?

until earlier today, the following snippet worked fine:
```starlark
archive_override(
    module_name = "aspect_rules_py",
    integrity = "sha256-DE4DI6ngyg2dG8Ydhr46bETo8BC1cYkycnUAoPIN4Xs=",
    strip_prefix = "rules_py-82ad68fe2e6ba695a528a8748a2f796c1da8c4c0",
    urls = "https://github.com/aspect-build/rules_py/archive/82ad68fe2e6ba695a528a8748a2f796c1da8c4c0.tar.gz",
)
```

Starting today, 28.02.2024 01:57 UTC, the sha256sum of this artifact changed to `sha256-3MlRecjYrEwN3/wzxtu+q7c7YMy1jNVTRa7LFjPgz28=`

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: 7.0.2

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: see above, latest commit

Language(s) and/or frameworks involved:

**Comment by mattem** [comment]
I'm not too sure what we can do here, those archives are generated by Github, and not something Aspect or rules_py controls.

This has previous happened, and Github released this [blog post](https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/) that noted their commitment to stability. I haven't seen other reports of this across the Bazel community however.

We are working on the release process for rules_py currently, so you can likely switch to a tagged release very soon.

**Comment by mattem** [comment]
Closing this as I don't think there's anything actionable on our side.
