### ISSUE TITLE
[FR]: provide convenience for 'uv pip compile'

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_py#300]
### What is the current behavior?

rules_python runs a Python program (pip-compile) which is very slow.

### Describe the feature

https://astral.sh/blog/uv is very fast. Not 100% compatible, but for a project willing to migrate to rules_py, that's okay.

**Comment by jab** [comment]
See also https://github.com/theoremlp/rules_uv, which provides a uv-powered `pip_compile` rule.

**Comment by jab** [comment]
Relatedly, since `uv` also speeds up virtualenv creation, if rules_py provides support for `uv`-based pip_compile, would it make sense to use `uv` to speed up virtualenv creation as well? (Would you like a separate ticket for that?)

**Comment by jab** [comment]
Opened a [new issue](https://github.com/aspect-build/rules_py/issues/345) for switching to `uv` for both features (now that I've hit a compatibility issue with rules_py's `venv` implementation), which would subsume this issue.

**Comment by alexeagle** [comment]
Since theoremlp/rules_uv exists for `uv pip compile`, the original intent here has been solved.
