### ISSUE TITLE
[Bug]: venv symlink creation can run into collisions

### ISSUE THREAD

**Issue by vors** [aspect-build/rules_py#335]
### What happened?

If there are wheels who define the same files then venv creation will fail.
Sometimes this is desirable, but often collision is on something silly like CHANGELOG.md and it would be good to somehow allow such problem to resolve without patching wheels

Repro https://github.com/aspect-build/rules_py/pull/334

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

bazel 7.0.2

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

0.7.2

Language(s) and/or frameworks involved:

### How to reproduce

```shell
https://github.com/aspect-build/rules_py/pull/334
```

**Comment by mattem** [comment]
Fun. Files at the wheel root, even outside of pure and plat lib, are allowed. `pip` seems to let the last one win when I tried it manually. Do other package managers warn or do the same thing?

**Comment by vors** [comment]
I only used pip extensively... never saw any warnings from it.
