### ISSUE TITLE
[Bug]: aspect_rules_py is incompatible with rules_poetry

### ISSUE THREAD

**Issue by luangong** [aspect-build/rules_py#338]
## What happened?

The `py_library`, `py_binary`, and `py_test` rules don’t work with [`rules_poetry`](https://registry.bazel.build/modules/rules_poetry). Packages installed by `poetry.parse()` can’t be included as dependencies of a `py_library`, `py_binary`, or `py_test` target.

## Version

- Development (host) and target OS/architectures: macOS on an Apple silicon Mac
- Output of `bazel --version`: bazel 7.1.1
- Version of the Aspect rules, or other relevant rules from your `WORKSPACE` or `MODULE.bazel` file: aspect_rules_py 0.7.3
- Language(s) and/or frameworks involved: Python, Poetry

## How to reproduce

Given the following minimal example:

```bazel
# MODULE.bazel
module(name = "poetry_demo", version = "0.1.0")

bazel_dep(name = "aspect_rules_py", version = "0.7.3")
bazel_dep(name = "rules_python", version = "0.31.0")

# Register a hermetic Python toolchain rather than rely on a locally-installed
# interpreter.
python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    configure_coverage_tool = True,
    is_default = True,
    python_version = "3.11",
)
use_repo(python, "python_3_11")

# https://registry.bazel.build/modules/rules_poetry
bazel_dep(name = "rules_poetry", version = "0.3.4")

poetry = use_extension("@rules_poetry//python:extensions.bzl", "poetry")
poetry.parse(
    name = "poetry",
    lock = "//:poetry.lock",
)
use_repo(poetry, "poetry")
```

```bazel
# BUILD.bazel
load("@aspect_rules_py//py:defs.bzl", "py_binary")

py_binary(
    name = "main",
    srcs = ["main.py"],
    deps = [
        "@poetry//:absl-py",
    ],
)
```

```toml
# pyproject.toml
[tool.poetry]
name = "poetry-demo"
version = "0.1.0"
authors = []
description = "Bazel Python example using Poetry"
package-mode = false

[tool.poetry.dependencies]
python = "~3.11"
absl-py = "^2.1.0"
```

```python
# main.py
from absl import app

def main(argv):
    print('Hello, Python and Poetry!')
    return 0

if __name__ == '__main__':
    app.run(main)
```

The build fails with the following error message:

```
ERROR: poetry-demo/BUILD.bazel:3:10: in deps attribute of py_binary rule //:main:
'@@rules_poetry~~poetry~poetry//:absl-py' does not have mandatory providers:
'PyInfo' or 'PyVirtualInfo'. Since this rule was created by the macro 'py_binary',
the error might have been caused by the macro implementation
```

However, `aspect_rules_py` works with `pip.parse`, and `rules_python` works with both `pip.parse` and `poetry.parse`. Here is the compatibility table:

| Extension Method | rules_python       | aspect_rules_py    |
|------------------|:------------------:|:------------------:|
| pip.parse        | :white_check_mark: | :white_check_mark: |
| poetry.parse     | :white_check_mark: | :x:                |

**Comment by mattem** [comment]
Alternatively, open an issue with rules_poetry to use the provider loaded from rules_python, rather than native as it'll hit up against this issue with other uses of `PyInfo`.

**Comment by oxidase** [comment]
I suggest to close it here as it relates to https://github.com/bazelbuild/rules_python/issues/1069#issuecomment-1942053014

Will fix in the rules repository
