### ISSUE TITLE
[Bug]: Wrong delimiter in conflict detection code?

### ISSUE THREAD

**Issue by tgeng** [aspect-build/rules_py#359]
### What happened?

When site-packages have conflicts, I am getting a panic like
```
==================== Test output for //path/to:some_test:
thread 'main' panicked at py/tools/py/src/pth.rs:146:14:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
================================================================================
```
Looking at the code it seems to me that the following line should be `site-packages` rather than `.runefiles/`

https://github.com/aspect-build/rules_py/blob/main/py/tools/py/src/pth.rs#L144

Apparently, `tgt` seems to be pointing to the "source" (for example `<execroot>/_main/bazel-out/k8-fastbuild/bin/external/some~external~module/some/pypi/package/site-packages/some/python/file.py`), so it won't contain any `.runfiles` in the path.

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:
> bazel version
Bazelisk version: v1.11.0
Build label: 7.2.0
Build target: @@//src/main/java/com/google/devtools/build/lib/bazel:BazelServer
Build time: Mon Jun 10 13:04:32 2024 (1718024672)
Build timestamp: 1718024672
Build timestamp as int: 1718024672

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
0.7.3

Language(s) and/or frameworks involved:
Python

### How to reproduce

```shell
I have two packages without almost identical content and they are both added to `deps` of a `py_test`. Then running `bazel test //path/to/the:test` fails with the above error from rust.
```

**Comment by tgeng** [comment]
any thoughts? @mattem

**Comment by tgeng** [comment]
gentle ping  @mattem  @alexeagle

**Comment by tgeng** [comment]
Also, can there be a lenient mode implemented? Basically overwrite the conflicting files in a deterministic way? That would align closer with how pip behaves and I would assume it will work generally since a lot of the conflicts are benign.

**Comment by mattem** [comment]
Can you provide more complete reproduction steps? I'm not clear on what the issue is here.

**Comment by tgeng** [comment]
Sure, here is a repro https://github.com/tgeng/pycross_venv_bug_repro

**Comment by ryanhsanthosh** [comment]
any update on this? i am having the same bug

**Comment by andyscott** [comment]
I'm also hitting the same issue but with airflow via `rules_pycross`.
