### ISSUE TITLE
[Bug]: "." added to imports by default

### ISSUE THREAD

**Issue by dizzy57** [aspect-build/rules_py#368]
### What happened?

`py_library`, `py_binary` and `py_test` macros set `imports` attribute to `["."]` by default. This pollutes top-level import namespace.
https://github.com/aspect-build/rules_py/blob/c37e67963502a401de4b117fa8104da2091b5d1c/py/defs.bzl

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: `bazel 7.0.2`

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: `HEAD` (`v0.7.3+`)

Language(s) and/or frameworks involved: none

### How to reproduce

```shell
Check out `rules_py` repository. Apply the following patch:


diff --git a/py/tests/repo_relative_imports/test/test.py b/py/tests/repo_relative_imports/test/test.py
index 8e87756..60a33da 100644
--- a/py/tests/repo_relative_imports/test/test.py
+++ b/py/tests/repo_relative_imports/test/test.py
@@ -1,3 +1,3 @@
-from py.tests.repo_relative_imports.lib import adder
+import adder

 assert adder.add(2, 3) == 5


Run `bazel test //py/tests/repo_relative_imports/test`.

Expected result: test fails since no top-level module `adder` is installed.
Actual result: test passes
```

### Any other information?

This is extremely problematic if instead of `adder.py` your users create `numpy.py`, since `import numpy` will import this file instead of `numpy` library.
`rules_python` defaults to `import = []`

**Comment by keunhong** [comment]
I am seeing this behavior in the current version (1.0.0), when I check `sys.path` from within Python the test's path is there for some reason, causing the same naming conflict issues.

Currently investigating where it's being added.
